categories:
- Genome annotation
description: 'rGREAT: Genomic Regions Enrichment of Annotations Tool.'
long_description: 'rGREAT: Genomic Regions Enrichment of Annotations Tool. Functional
  enrichment analysis directly performed on genomic regions.'
name: rgreat
owner: jobucher
remote_repository_url: https://github.com/jonasbucherETH/galaxy/blob/dev/tools/my_tools/rgreat/.shed.yml
